"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import {
  GraduationCap,
  User,
  Lock,
  Eye,
  EyeOff,
  Info,
} from "lucide-react";

export default function StudentLoginCard() {
  const router = useRouter();

  const [studentId, setStudentId] = useState("");
  const [password, setPassword] = useState("");

  const [showPassword, setShowPassword] = useState(false);
  const [rememberMe, setRememberMe] = useState(false);

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handleLogin = async (
    e: React.FormEvent<HTMLFormElement>
  ) => {
    e.preventDefault();

    setError("");

    if (!studentId.trim()) {
      setError("Please enter your Student ID.");
      return;
    }

    if (!password.trim()) {
      setError("Please enter your password.");
      return;
    }

    try {
      setLoading(true);

      // Backend API will be connected later
      await new Promise((resolve) => setTimeout(resolve, 1500));

      console.log({
        studentId,
        password,
        rememberMe,
      });

      router.push("/student/dashboard");
    } catch {
      setError("Unable to login. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex items-center justify-center p-10 lg:p-14">

      <div className="w-full max-w-md">

        {/* Heading */}

        <div className="text-center mb-8">

          <div className="w-16 h-16 mx-auto rounded-full bg-blue-100 flex items-center justify-center">

            <GraduationCap className="text-blue-600 w-8 h-8" />

          </div>

          <h2 className="text-4xl font-bold text-slate-900 mt-5">
            Student Login
          </h2>

          <p className="text-slate-500 mt-3">
            Login using the credentials provided by your school.
          </p>

        </div>

        {/* Notice */}

        <div className="flex gap-3 bg-blue-50 border border-blue-100 rounded-xl p-4 mb-8">

          <Info className="text-blue-600 mt-1" />

          <p className="text-sm text-slate-600 leading-6">

            Student ID and Password are generated by your School Administrator.

          </p>

        </div>

        {/* Form */}

        <form onSubmit={handleLogin} className="space-y-6">

          {/* Student ID */}

          <div>

            <label className="block font-semibold text-slate-700 mb-2">
              Student ID
            </label>

            <div className="relative">

              <User className="absolute left-4 top-4 text-slate-400" />

              <input
                type="text"
                value={studentId}
                onChange={(e) => setStudentId(e.target.value)}
                placeholder="Enter Student ID"
                className="w-full rounded-xl border border-slate-300 py-4 pl-12 pr-4 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100 transition"
              />

            </div>

          </div>

          {/* Password */}

          <div>

            <label className="block font-semibold text-slate-700 mb-2">
              Password
            </label>

            <div className="relative">

              <Lock className="absolute left-4 top-4 text-slate-400" />

              <input
                type={showPassword ? "text" : "password"}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Enter Password"
                className="w-full rounded-xl border border-slate-300 py-4 pl-12 pr-12 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100 transition"
              />

              <button
                type="button"
                onClick={() =>
                  setShowPassword(!showPassword)
                }
                className="absolute right-4 top-4 text-slate-500"
              >
                {showPassword ? (
                  <EyeOff />
                ) : (
                  <Eye />
                )}
              </button>

            </div>

          </div>

          {/* Remember */}

          <div className="flex items-center justify-between">

            <label className="flex items-center gap-2">

              <input
                type="checkbox"
                checked={rememberMe}
                onChange={(e) =>
                  setRememberMe(e.target.checked)
                }
              />

              <span className="text-slate-600">
                Remember Me
              </span>

            </label>

            <button
              type="button"
              className="text-blue-600 hover:underline"
            >
              Forgot Password?
            </button>

          </div>

          {/* Error */}

          {error && (
            <div className="bg-red-50 border border-red-200 rounded-xl p-4">
              <p className="text-red-600 text-sm">
                {error}
              </p>
            </div>
          )}

          {/* Login */}

          <button
            type="submit"
            disabled={loading}
            className="w-full rounded-xl bg-blue-600 hover:bg-blue-700 text-white py-4 font-semibold transition disabled:opacity-60"
          >

            {loading ? (
              <div className="flex justify-center items-center gap-3">

                <div className="h-5 w-5 border-2 border-white border-t-transparent rounded-full animate-spin" />

                Logging in...

              </div>
            ) : (
              "Login"
            )}

          </button>

        </form>

        {/* Divider */}

        <div className="flex items-center my-8">

          <div className="flex-1 h-px bg-slate-300" />

          <span className="px-4 text-slate-400 text-sm">
            OR
          </span>

          <div className="flex-1 h-px bg-slate-300" />

        </div>

        {/* School Code */}

        <button className="w-full border-2 border-blue-600 text-blue-600 rounded-xl py-4 font-semibold hover:bg-blue-600 hover:text-white transition">

          Login using School Code

        </button>

        {/* Footer */}

        <p className="text-center text-slate-500 mt-8 text-sm leading-6">

          Need help logging in?

          <br />

          Contact your School Administrator or Class Teacher.

        </p>

      </div>

    </div>
  );
}